# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0007_auto_20180104_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В разработке'), ('testing', 'В тестировании'), ('production', 'В исполнении'), ('closed', 'Закрыта')], default='open', max_length=255, verbose_name='статус'),
        ),
    ]
