version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    restart: always
    build: web/
    volumes:
      - /root/media:/var/www/media
    depends_on:
      - postgres
  nginx:
    build: nginx/
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/certs:/certs
      - /root/acme-challenges:/acme-challenges
      - /root/media:/var/www/media
    depends_on:
      - web
volumes:
  pgdata:
